name: Deploy

on:
  push:
    branches:
      - dev # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      env: 
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > keyfile
        chmod 600 keyfile
        ssh-keyscan -H ec2-13-55-195-185.ap-southeast-2.compute.amazonaws.com >> ~/.ssh/known_hosts

    - name: SSH and deploy
      run: ssh -t -i keyfile ubuntu@ec2-13-55-195-185.ap-southeast-2.compute.amazonaws.com "sudo bash ~/deploy.sh"
