name: Deploy

on:
  push:
    branches:
      - dev # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH host to known hosts
      run: ssh-keyscan -H ec2-13-55-195-185.ap-southeast-2.compute.amazonaws.com >> ~/.ssh/known_hosts

    - name: SSH and deploy
      run: ssh -t -i ~/.ssh/id_rsa ubuntu@ec2-13-55-195-185.ap-southeast-2.compute.amazonaws.com "sudo bash ~/deploy.sh"
